#!/usr/bin/env python

def frequent():
   count={}
   for i in array:
      if count.has_key(i):
         coount[i] += 1
   print count
   length=len(count)-1
   for i in range(len(count)):
      if count[i] > count[i+1]:
         count[i],count[i+1] = count[i+1],count[i]
   print count
    
array = [ 1, 4, 4, 5, 5, 5, 6]
frequent()
       
